services:
  silverbullet:
    build: .
    container_name: silverbullet
    restart: unless-stopped

    environment:
      SB_USER: admin:admin

    volumes:
      - /mnt/iCloud/8. Knowledge:/space/Knowledge
      - ./Configuration:/space/Configuration
      - ./Library:/space/Library
    ports:
      - "3000:3000"
